### ISSUE TITLE
Error when running the demo code

### ISSUE THREAD

**Issue by iz2late** [MatthieuFP/zerommt#1]
Thank you for the excellent work and benchmark! When I run the example code (without cfg) on V100 GPUs:

```
Traceback (most recent call last):
  File "/home/ubuntu/efs/xxx/models/zerommt/test.py", line 24, in <module>
    loss = model(imgs=[image],
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/zerommt/main.py", line 84, in forward
    outputs = self.mmt_model(input_ids=src_inps.input_ids, input_visual_features=img_features,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/zerommt/modeling.py", line 177, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/adapters/context.py", line 116, in wrapper_func
    results = f(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/adapters/model_mixin.py", line 1270, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/zerommt/modeling.py", line 258, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/xxx/models/zerommt/zerommt/modeling.py", line 398, in forward
    inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/opt/conda/envs/mmt/lib/python3.11/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by MatthieuFP** [comment]
Hi, thanks for your interest in our work and for pointing out the bug. Indeed, a "model.to(device)" is missing in the demo. I modified the README accordingly. Should work smoothly now.

Best,
Matthieu
